name: Build Wine and FEX for Android 2 (dunkly)

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r26b  # Version of the NDK to use
      ANDROID_NDK_HOME: ${{ env.TEMP }}/android-ndk-${{ env.NDK_VERSION }}
      TOOLCHAIN: ${{ env.TEMP }}/toolchain

    steps:
      - name: Checkout only workflow files
        uses: actions/checkout@v2
        with:
          path: .github

      # Git clone Wine repository
      - name: Clone Wine repository
        run: |
          git clone https://github.com/wine-mirror/wine.git

      # Git clone FEX repository
      - name: Clone FEX repository
        run: |
          git clone https://github.com/FEX-Emu/FEX.git

      # Download and configure Android NDK
      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
          unzip android-ndk-${{ env.NDK_VERSION }}-linux.zip -d ${{ env.TEMP }}

      - name: Set up Android toolchain
        run: |
          $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir ${{ env.TOOLCHAIN }}

      # Install dependencies for building Wine and FEX
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libx11-dev libxinerama-dev libfreetype6-dev libglu1-mesa-dev libosmesa6-dev cmake

      # Build Wine for Android
      - name: Compile Wine for Android
        run: |
          cd wine
          ./configure --host=aarch64-linux-android --prefix=/wine-android
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/wine-build

      # Build FEX for Android
      - name: Compile FEX for Android
        run: |
          cd FEX
          mkdir build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/fex-build

      # Create ZIP with Wine and FEX
      - name: Create ZIP with Wine and FEX
        run: |
          mkdir output
          cp -r $GITHUB_WORKSPACE/wine-build/* output/
          cp -r $GITHUB_WORKSPACE/fex-build/* output/
          zip -r wine_fex_android_build.zip output/

      # Upload the ZIP file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wine-fex-android
          path: wine_fex_android_build.zip
