name: Build Wine and FEX for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r26b  # Versão do NDK que deseja usar
      ANDROID_NDK_HOME: ${{ runner.temp }}/android-ndk-$NDK_VERSION
      TOOLCHAIN: ${{ runner.temp }}/toolchain

    steps:
      - name: Checkout only workflow files
        uses: actions/checkout@v2
        with:
          path: .github

      # Git clone do Wine
      - name: Clone Wine repository
        run: |
          git clone https://github.com/wine-mirror/wine.git

      # Git clone do FEX
      - name: Clone FEX repository
        run: |
          git clone https://github.com/FEX-Emu/FEX.git

      # Baixar e configurar o Android NDK
      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
          unzip android-ndk-${{ env.NDK_VERSION }}-linux.zip -d ${{ runner.temp }}

      - name: Set up Android toolchain
        run: |
          $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir ${{ env.TOOLCHAIN }}

      # Instalar dependências para compilar o Wine e FEX
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libx11-dev libxinerama-dev libfreetype6-dev libglu1-mesa-dev libosmesa6-dev cmake

      # Compilar Wine para Android
      - name: Compile Wine for Android
        run: |
          cd wine
          ./configure --host=aarch64-linux-android --prefix=/wine-android
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/wine-build

      # Compilar FEX para Android
      - name: Compile FEX for Android
        run: |
          cd FEX
          mkdir build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/fex-build

      # Compactar Wine e FEX em um arquivo .zip
      - name: Create ZIP with Wine and FEX
        run: |
          mkdir output
          cp -r $GITHUB_WORKSPACE/wine-build/* output/
          cp -r $GITHUB_WORKSPACE/fex-build/* output/
          zip -r wine_fex_android_build.zip output/

      # Fazer upload do arquivo .zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wine-fex-android
          path: wine_fex_android_build.zip
