name: Setup TeamViewer QuickSupport

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  setup-teamviewer:
    runs-on: windows-latest

    steps:
      - name: Baixar TeamViewer QuickSupport
        run: |
          Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewerQS_x64.exe" -OutFile "TeamViewerQS.exe"

      - name: Instalar TeamViewer QuickSupport
        run: |
          Start-Process -FilePath "TeamViewerQS.exe" -ArgumentList "/S" -Wait

      - name: Iniciar TeamViewer
        run: |
          Start-Process -FilePath "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"

      - name: Mostrar informações de conexão
        run: |
          # Aguarda 10 segundos para o TeamViewer iniciar e então mostra informações
          Start-Sleep -Seconds 10
          $teamViewerId = Get-Content "$env:APPDATA\TeamViewer\TeamViewerQS.ini" | Select-String -Pattern "ClientID" | ForEach-Object { $_.ToString().Split('=')[1].Trim() }
          Write-Host "Para conectar ao TeamViewer, use o seguinte ID:"
          Write-Host "ID do TeamViewer: $teamViewerId"
          Write-Host "Acesso: Verifique a senha no aplicativo TeamViewer."
      
      - name: Manter o processo em execução
        run: |
          while ($true) {
            Write-Host "Serviço do TeamViewer em execução. Aguardando conexões..."
            Start-Sleep -Seconds 3600  # Aguardando 1 hora entre iterações
          }
