name: Build VirtualGL for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-20.04

    services:
      qemu:
        image: multiarch/qemu-user-static
        options: --privileged
        volumes:
          - /dev:/dev
        ports:
          - 12345:12345

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static binfmt-support debootstrap schroot

      - name: Set up ARM environment
        run: |
          sudo apt-get install -y qemu-user-static
          sudo update-binfmts --enable qemu-arm
          sudo update-binfmts --enable qemu-aarch64

      - name: Install dependencies for building VirtualGL
        run: |
          sudo apt-get install -y build-essential cmake libjpeg-dev libx11-dev libxext-dev

      - name: Build VirtualGL for ARM64
        run: |
          sudo qemu-aarch64-static /bin/bash -c "
          sudo apt-get update &&
          sudo apt-get install -y dpkg-dev debhelper &&
          mkdir -p virtualgl-arm64 &&
          cd virtualgl-arm64 &&
          cmake .. &&
          make &&
          make package &&
          sudo dpkg-deb --build ./path_to_build_output_arm64
          "

      - name: Build VirtualGL for ARM32
        run: |
          sudo qemu-arm-static /bin/bash -c "
          sudo apt-get update &&
          sudo apt-get install -y dpkg-dev debhelper &&
          mkdir -p virtualgl-arm32 &&
          cd virtualgl-arm32 &&
          cmake .. &&
          make &&
          make package &&
          sudo dpkg-deb --build ./path_to_build_output_arm32
          "

      - name: Upload ARM64 .deb package
        uses: actions/upload-artifact@v3
        with:
          name: virtualgl-arm64.deb
          path: ./virtualgl-arm64/path_to_build_output_arm64/virtualgl-arm64.deb

      - name: Upload ARM32 .deb package
        uses: actions/upload-artifact@v3
        with:
          name: virtualgl-arm32.deb
          path: ./virtualgl-arm32/path_to_build_output_arm32/virtualgl-arm32.deb
