name: Build VirtualGL for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-20.04

    services:
      qemu:
        image: multiarch/qemu-user-static
        options: --privileged
        volumes:
          - /dev:/dev
        ports:
          - 12345:12345

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static debootstrap schroot binfmt-support
          sudo update-binfmts --enable qemu-arm
          sudo update-binfmts --enable qemu-aarch64

      - name: Create ARM64 environment with debootstrap
        run: |
          sudo debootstrap --arch=arm64 focal /tmp/arm64-chroot http://ports.ubuntu.com/ubuntu-ports/
          sudo cp /usr/bin/qemu-aarch64-static /tmp/arm64-chroot/usr/bin/

      - name: Create ARM32 environment with debootstrap
        run: |
          sudo debootstrap --arch=armhf focal /tmp/arm32-chroot http://ports.ubuntu.com/ubuntu-ports/
          sudo cp /usr/bin/qemu-arm-static /tmp/arm32-chroot/usr/bin/

      - name: Install dependencies for ARM64 in chroot
        run: |
          sudo chroot /tmp/arm64-chroot /bin/bash -c "
          apt-get update &&
          apt-get install -y build-essential cmake libjpeg-dev libx11-dev libxext-dev dpkg-dev debhelper"

      - name: Install dependencies for ARM32 in chroot
        run: |
          sudo chroot /tmp/arm32-chroot /bin/bash -c "
          apt-get update &&
          apt-get install -y build-essential cmake libjpeg-dev libx11-dev libxext-dev dpkg-dev debhelper"

      - name: Build VirtualGL for ARM64
        run: |
          sudo chroot /tmp/arm64-chroot /bin/bash -c "
          git clone https://github.com/VirtualGL/virtualgl.git &&
          cd virtualgl &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make &&
          make package &&
          dpkg-deb --build ../build"

      - name: Build VirtualGL for ARM32
        run: |
          sudo chroot /tmp/arm32-chroot /bin/bash -c "
          git clone https://github.com/VirtualGL/virtualgl.git &&
          cd virtualgl &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make &&
          make package &&
          dpkg-deb --build ../build"

      - name: Upload ARM64 .deb package
        uses: actions/upload-artifact@v3
        with:
          name: virtualgl-arm64.deb
          path: /tmp/arm64-chroot/virtualgl/build/virtualgl-arm64.deb

      - name: Upload ARM32 .deb package
        uses: actions/upload-artifact@v3
        with:
          name: virtualgl-arm32.deb
          path: /tmp/arm32-chroot/virtualgl/build/virtualgl-arm32.deb
