name: Setup SSH on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Update and install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          sudo ufw allow ssh

      - name: Show SSH connection info
        run: |
          echo "Server is ready for SSH connection"
          echo "-----------------------------------"
          echo "Username: $USER"
          echo "IP Address: $(curl ifconfig.me)"
          echo "SSH Port: 22 (default)"
          echo "-----------------------------------"

      - name: Keep job running for 1 day
        run: |
          sleep 86400
