name: Setup RDP and Generate RDP File

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Instalar RDP
        run: |
          # Neste caso, o RDP já deve estar disponível na imagem do Windows, então não há instalação adicional necessária.
          Write-Host "RDP já está disponível na imagem do Windows."

      - name: Configurar RDP e gerar arquivo .rdp
        run: |
          $rdpFilePath = "C:\Users\runneradmin\Desktop\MyConnection.rdp"
          $rdpContent = @"
          full address:s:localhost:3389
          username:s:Administrator
          redirectclipboard:i:1
          security:transport
          administrative session:i:1
          "@
          $rdpContent | Out-File -FilePath $rdpFilePath -Encoding ASCII
          Write-Host "Arquivo RDP gerado em: $rdpFilePath"

      - name: Publicar arquivo RDP como artefato
        uses: actions/upload-artifact@v3
        with:
          name: MyConnection
          path: C:\Users\runneradmin\Desktop\MyConnection.rdp

      - name: Manter o processo em execução
        run: |
          Write-Host "O job está ativo e aguardando por conexões RDP."
          # Manter o job ativo por 1 dia (86400 segundos)
          Start-Sleep -Seconds 86400
