name: Install AnyDesk and Keep Running

on:
  push:
    branches:
      - main

jobs:
  install-anydesk:
    runs-on: windows-latest
    steps:
      - name: Download AnyDesk
        run: |
          Invoke-WebRequest -Uri "https://download.anydesk.com/downloads/AnyDesk.exe" -OutFile "C:\AnyDesk.exe"

      - name: Install AnyDesk
        run: |
          Start-Process -FilePath "C:\AnyDesk.exe" -ArgumentList "/install /quiet" -Wait

      - name: Start AnyDesk
        run: |
          Start-Process "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
          Start-Sleep -Seconds 5  # Aguardar para garantir que o AnyDesk inicie

      - name: Display AnyDesk ID and Connection Info
        run: |
          # Aguarda um tempo para o AnyDesk inicializar completamente
          Start-Sleep -Seconds 10
          
          # Mostra o ID do AnyDesk
          $anyDeskID = Get-Content "C:\Program Files (x86)\AnyDesk\ad.ini" | Select-String "id" | ForEach-Object { $_.ToString().Split('=')[1] }
          Write-Host "AnyDesk ID: $anyDeskID"

      - name: Keep Job Active
        run: |
          # Manter o job ativo por 24 horas
          Start-Sleep -Seconds 86400
