name: Setup RDP on Windows

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Ativar Remote Desktop
        run: |
          # Ativar Remote Desktop e permitir conexões
          $rdpKey = "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server"
          Set-ItemProperty -Path $rdpKey -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path $rdpKey -Name "UserAuthentication" -Value 1

      - name: Configurar Firewall
        run: |
          # Permitir conexões RDP no firewall
          New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -Action Allow -LocalPort 3389

      - name: Mostrar Endereço IP
        run: |
          # Mostrar o endereço IP na tela
          Get-NetIPAddress | Where-Object { $_.AddressFamily -eq "IPv4" } | Select-Object IPAddress

      - name: Manter job ativo
        run: |
          # Manter o job ativo, sem loop infinito
          Write-Host "O job está ativo. Você pode visualizar as saídas acima."
          Start-Sleep -Seconds 86400  # Esperar por um dia (86400 segundos)
