name: Run TeamViewer Setup

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  setup-teamviewer:
    runs-on: windows-latest

    steps:
      - name: Baixar TeamViewer
        run: |
          Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewer.exe" -OutFile "TeamViewer.exe"

      - name: Instalar TeamViewer
        run: |
          Start-Process -FilePath "TeamViewer.exe" -ArgumentList "/S" -Wait

      - name: Manter o processo em execução
        run: |
          for ($i=0; $i -lt 24; $i++) {
            Write-Host "Executando loop número $($i + 1) - Aguardando 1 hora."
            Start-Sleep -Seconds 3600  # Aguardando 1 hora
          }

      - name: Mostrar informações de conexão
        run: |
          $teamViewerId = Get-Content "$env:APPDATA\TeamViewer\TeamViewer.ini" | Select-String -Pattern "ClientID" | ForEach-Object { $_.ToString().Split('=')[1].Trim() }
          Write-Host "Para conectar ao TeamViewer, use o seguinte ID:"
          Write-Host "ID do TeamViewer: $teamViewerId"
          Write-Host "Acesso: Verifique a senha no aplicativo TeamViewer."
