name: Ubuntu Remote Desktop (RDP)

on: 
  workflow_dispatch:  # Permite iniciar o workflow manualmente

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest  # Usa o runner padrão do GitHub (x86_64)

    steps:
      - name: Atualizar e instalar pacotes necessários
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          
          # Ativar e iniciar o serviço xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          # Configura a sessão XFCE4 para o RDP
          echo "xfce4-session" > ~/.xsession
          sudo service xrdp restart
        shell: bash

      - name: Definir senha do usuário padrão
        run: |
          # Define a senha para o usuário "runner" (alterar conforme preferir)
          sudo useradd -m -s /bin/bash myuser
          echo 'myuser:mysuperpassword' | sudo chpasswd
          sudo adduser myuser ssl-cert  # Adiciona o usuário ao grupo necessário para o xrdp
        shell: bash

      - name: Exibir informações de conexão (Endereço IP, usuário e senha)
        run: |
          # Obter o endereço IP público da instância
          IP=$(curl -s http://ifconfig.me)
          echo "Conecte-se ao servidor usando os seguintes detalhes:"
          echo "Endereço IP: $IP"
          echo "Usuário: myuser"
          echo "Senha: mysuperpassword"
        shell: bash

      - name: Manter o servidor ativo por 1 dia
        run: |
          echo "Mantendo o servidor rodando por 24 horas..."
          sleep 86400  # Pausa por 24 horas
        shell: bash
