name: Setup RDP and Generate RDP File

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Baixar e instalar RDP
        run: |
          # O RDP já vem instalado na imagem do Windows do GitHub Actions, então essa etapa é opcional.
          Write-Host "RDP já está disponível na imagem do Windows."

      - name: Iniciar o servidor RDP
        run: |
          # Iniciar o serviço de RDP
          Start-Service -Name "TermService"
          Write-Host "Servidor RDP iniciado."

      - name: Configurar RDP e gerar arquivo .rdp
        run: |
          $rdpFilePath = "C:\Users\runneradmin\Desktop\MyConnection.rdp"
          $rdpContent = @"
          full address:s:localhost:3389
          username:s:Administrator
          redirectclipboard:i:1
          security:transport
          administrative session:i:1
          "@
          $rdpContent | Out-File -FilePath $rdpFilePath -Encoding ASCII
          Write-Host "Arquivo RDP gerado em: $rdpFilePath"

      - name: Exibir conteúdo do arquivo RDP
        run: |
          $rdpFilePath = "C:\Users\runneradmin\Desktop\MyConnection.rdp"
          $content = Get-Content -Path $rdpFilePath
          Write-Host "Conteúdo do arquivo RDP:"
          Write-Host $content

      - name: Publicar arquivo RDP como artefato
        uses: actions/upload-artifact@v3
        with:
          name: MyConnection
          path: C:\Users\runneradmin\Desktop\MyConnection.rdp

      - name: Manter o processo em execução
        run: |
          Write-Host "O job está ativo e aguardando por conexões RDP."
          # Manter o job ativo por 1 dia (86400 segundos)
          Start-Sleep -Seconds 86400
